# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='photo',
            field=models.TextField(default='none', max_length=75),
        ),
    ]
