# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0003_auto_20171022_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
