# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0006_auto_20171024_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.FileField(upload_to='photos'),
        ),
    ]
