# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-24 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0007_auto_20171024_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.TextField(default='admin/img/Eva.JPG', max_length=75),
        ),
    ]
