# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0008_auto_20171024_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.ImageField(upload_to='photos_des_eleves'),
        ),
    ]
