# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0009_auto_20171025_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.TextField(max_length=150),
        ),
    ]
