# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0010_auto_20171025_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='courriel_parents_2',
            field=models.TextField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_parents_2',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom_parents_2',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_parents_2',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
