# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0011_auto_20171105_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='courriel_parents_1',
            field=models.TextField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_eleve',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_parents_1',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom_eleve',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenom_parents_1',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_parents_1',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
