# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classe_de_fanie', '0012_auto_20171108_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='enseignant',
            field=models.BooleanField(default=False),
        ),
    ]
